services:
  mongodb8:
    image: mongo:8
    container_name: jobnoc-mongo8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password}
    volumes:
      - mongo8_data:/data/db
    ports:
      - "127.0.0.1:27017:27017" # Only accessible from localhost
    restart: always

  redis7:
    image: redis:latest
    container_name: jobnoc-redis7
    ports:
      - "127.0.0.1:6379:6379" # Only accessible from localhost
    restart: always

volumes:
  mongo8_data:
