services:
  mongodb8:
    image: mongo:8
    container_name: jobnoc-mongo8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-Pass@1108}
    volumes:
      - mongo8_data:/data/db
    ports:
      - "127.0.0.1:27018:27017" # Map host port 27018 to container port 27017
    restart: always

  redis7:
    image: redis:latest
    container_name: jobnoc-redis7
    ports:
      - "127.0.0.1:6380:6379" # Map host port 6380 to container port 6379
    restart: always

volumes:
  mongo8_data:
